### PR TITLE
Update versions for pyansys metapackage

### PR DESCRIPTION
**Pull request by RobPasMue**
Preparing for Ansys 23R1

### CODE REVIEW

**Comment by RobPasMue** [comment]
Had to manually update all reqs. Python <4.0 blocker on requirements was causing dependabot to not update automatically. Let's remove it for now so that we don't have to manually do it. I leave auto-merge enabled - so when approved it will be merged. Latest versions have been set.

**Comment by RobPasMue** [comment]
Once this branch merges, I will update PR #42 to allow for Python 3.10.

**Comment by RobPasMue** [comment]
Looking for approval here @jorgepiloto @MaxJPRey @akaszynski

**Review by akaszynski — COMMENTED** [review]
LGTM, and we should consider a release soon.

**Comment by RobPasMue** [comment]
> LGTM, and we should consider a release soon.

Great, sounds good to me too. Planning on it for next week. @akaszynski I need approval to merge.. not just review

**Pull request merged**
