### PR TITLE
Python 3.11 support

### PR DESCRIPTION
**Pull request by RobPasMue**
As title says

### CODE REVIEW

**Comment by RobPasMue** [comment]
Do not merge this PR

**Comment by RobPasMue** [comment]
Looks like only one dependency is missing - [h5py](https://github.com/h5py/h5py)

Apparently, building the wheel from source is not enough... so we might have to wait until a Python 3.11 release is available on their side. #AlmostThere

**Comment by RobPasMue** [comment]
Hell yeah.. finally h5py updated their wheels! We are good to go =) @jorgepiloto @MaxJPRey please review whenever possible.

**Review by jorgepiloto — APPROVED** [review]
Welcome Python 3.11! 🐍

**Pull request merged**
