### PR TITLE
Rework docs

### PR DESCRIPTION
**Pull request by akaszynski**
Rework documenation to include:

- [x] Main landing page that contains a description of the PyAnsys project.
- [x] Use `sphinx-design` with various icons for the projects, as it currently is on docs.pyansys.com
- [x] Add the four main headers to the top of the docs (e.g. Getting Started, User Guide, API Reference, Examples). This will help establish consistency with other PyAnsys libraries. These pages should effectively repeat and refer to other libraries documentation, but provide enough information so users can evaluate if PyAnsys is right for them.
- [x] Incorporate the new versioning system.

### CODE REVIEW

**Comment by RobPasMue** [comment]
Some comments...
> - [ ]  Main landing page that contains a description of the PyAnsys project.

Isn't this the PyAnsys landing page hosted at docs.pyansys.com? I wouldn't duplicate efforts...

In fact, this brings me to my next point...

- Should https://github.com/pyansys/landing-page and this repo be the same one? It seems to me that we are going to host the same information as the PyAnsys landing page + some extra details on how the versioning scheme for the ``pyansys`` metapackage works,

**Comment by jorgepiloto** [comment]
I agree with @RobPasMue, we should collect all the documentation under a common repository, giving preference to this one.

**Comment by RobPasMue** [comment]
Following the previous discussion, I'll be doing the following:
- [ ] Removing the [pyansys/landing-page](https://github.com/pyansys/landing-page) repository in favor of the PyAnsys metapackage
- [ ] Moving CNAME to this repository
- [ ] Ensure that the points from https://github.com/pyansys/pyansys/pull/118#issue-1504801466 are fulfilled

Pinging @akaszynski for visibility

**Comment by RobPasMue** [comment]
> - [ ] Add the four main headers to the top of the docs (e.g. Getting Started, User Guide, API Reference, Examples). This will help establish consistency with other PyAnsys libraries. These pages should effectively repeat and refer to other libraries documentation, but provide enough information so users can evaluate if PyAnsys is right for them.

I'm also having a hard time understanding what to include in API Reference or Examples for this landing page... the PyAnsys metapackage is not expected to have an API or examples...

What we could do is generate a new grid/table-like page which links to the examples of each of the subpackages... The same for the APIs... or even the User Guides.

The PyAnsys metapackage itself does not provide any functionality - it is only a way of grouping together the PyAnsys ecosystem packages. It only contains information regarding the version of the metapackage. This is already explained in the Getting Started section thanks to @jorgepiloto.

Would you agree with this approach?

**Review by RobPasMue — APPROVED** [review]

**Comment by akaszynski** [comment]
> I'm also having a hard time understanding what to include in API Reference or Examples for this landing page... the PyAnsys metapackage is not expected to have an API or examples...

Reasonable, though we could probably provide a brief overview of other packages APIs in a smart way... or just do what you did and point out that you should really reference the rest of the pyansys documentation.

@RobPasMue, As a follow-up, let's put better pictures on the landing and reference pages.

**Comment by RobPasMue** [comment]
Sure, let me open a new issue for this.

> @RobPasMue, As a follow-up, let's put better pictures on the landing and reference pages.

**Pull request merged**
